version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
  app:
    build: .
    container_name: api_restaurant
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/restaurante
